### ISSUE TITLE
24 sec audio, jukebox representation size?

### ISSUE THREAD

**Issue by marypilataki** [rodrigo-castellon/jukemirlib#2]
Hello,

Thank you very much for making this library available and making it straightforward to extract Jukebox representations :)

I would like to ask regarding the shape of a representation for 24 seconds of audio. In your paper you mention that you use mean pooling across time to get an output representation of 72 × 4800 for 24 seconds of audio.
Is this implemented in the library? When I use jukemir.extract() with the default settings, I get  a representation of 8192 x 4800 for 24 secs of audio instead. Am I misunderstanding something here?

Cheers!
Mary

**Comment by rodrigo-castellon** [comment]
Hi!
Thanks for your interest.

This is implemented in the library, but extracting representations from all 72 layers can be cumbersome, so the default is to extract only from layer 36. To extract from all layers, just do:
```python
reps = jukemirlib.extract(audio, layers=list(range(1, 73)))
```

Note that the layers numbers are 1-indexed (see https://github.com/rodrigo-castellon/jukemirlib/blob/main/jukemirlib/lib.py#L208).

Also, mean-pooling is not applied unless you specifically ask for it with `meanpool=True`. Both asking for mean-pooling and extracting from all layers in combination will give you a set of 72 arrays, each of which is of size `(4800,)`.

**Comment by marypilataki** [comment]
Hey,

Thank you very much for the prompt response, that makes total sense!
For some reason, I thought that the default settings would correspond to the way you describe the extraction method in the paper. But obviously that doesn't have to be the case :)

I will close this issue.

Thanks again,
Mary
